// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3IReM5lT0Auiw9H538oNEgPpj4tTtSxw',
    appId: '1:119956789984:web:ba8081198a76d82b6e0e85',
    messagingSenderId: '119956789984',
    projectId: 'freshga-homemades',
    authDomain: 'freshga-homemades.firebaseapp.com',
    storageBucket: 'freshga-homemades.firebasestorage.app',
    measurementId: 'G-M7S78FF1RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwEnmNo5y69fpp1eCZcUIXhypSkHJQ1FA',
    appId: '1:119956789984:android:9755d7665c1c9f3d6e0e85',
    messagingSenderId: '119956789984',
    projectId: 'freshga-homemades',
    storageBucket: 'freshga-homemades.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhpA9j9i9_OSGf7AnoH5RVzjoA8eSkwLU',
    appId: '1:119956789984:ios:84ec592a3e9f63946e0e85',
    messagingSenderId: '119956789984',
    projectId: 'freshga-homemades',
    storageBucket: 'freshga-homemades.firebasestorage.app',
    iosBundleId: 'com.example.freshgaHomemades',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhpA9j9i9_OSGf7AnoH5RVzjoA8eSkwLU',
    appId: '1:119956789984:ios:84ec592a3e9f63946e0e85',
    messagingSenderId: '119956789984',
    projectId: 'freshga-homemades',
    storageBucket: 'freshga-homemades.firebasestorage.app',
    iosBundleId: 'com.example.freshgaHomemades',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3IReM5lT0Auiw9H538oNEgPpj4tTtSxw',
    appId: '1:119956789984:web:176e77da6c4d88c36e0e85',
    messagingSenderId: '119956789984',
    projectId: 'freshga-homemades',
    authDomain: 'freshga-homemades.firebaseapp.com',
    storageBucket: 'freshga-homemades.firebasestorage.app',
    measurementId: 'G-HVDK9BTMRT',
  );
}
