import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../models/address_model.dart';
import '../../../models/order_model.dart';
import '../../../providers/cart_provider.dart';
import '../../../providers/customer_provider.dart';
import '../../../services/order_service.dart';
import '../../../core/theme/app_colors.dart';
import 'order_success_screen.dart';

class PaymentScreen extends StatefulWidget {
  final String storeId;
  final String storeName;
  final List<OrderItem> items;
  final AddressModel deliveryAddress;
  final double subtotal;
  final double deliveryFee;
  final double totalToPay;
  final String instructions;

  const PaymentScreen({
    Key? key,
    required this.storeId,
    required this.storeName,
    required this.items,
    required this.deliveryAddress,
    required this.subtotal,
    required this.deliveryFee,
    required this.totalToPay,
    this.instructions = '',
  }) : super(key: key);

  @override
  State<PaymentScreen> createState() => _PaymentScreenState();
}

class _PaymentScreenState extends State<PaymentScreen> {
  String _selectedMethod = 'COD';
  bool _isProcessing = false;

  void _showComingSoon() {
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text("This payment method is coming soon! Please use Cash on Delivery for now."),
        duration: Duration(seconds: 2),
      )
    );
  }

  Future<void> _placeOrder() async {
    if (_selectedMethod != 'COD') {
      _showComingSoon();
      return;
    }

    setState(() => _isProcessing = true);

    try {
      final orderService = OrderService();
      
      // Calculate SLA timings
      int maxDispatchDays = 1; // Default
      // In a real scenario, we'd pass dispatch times in OrderItem, but for now we fallback to 2 days if unknown
      final maxDispatchDate = DateTime.now().add(const Duration(days: 2));
      final expiresAt = DateTime.now().add(const Duration(hours: 24)); // 24h SLA

      final customerProvider = Provider.of<CustomerProvider>(context, listen: false);
      final customerId = customerProvider.currentCustomer?.uid ?? 'unknown_customer';

      final order = OrderModel(
        orderId: '', // Will be generated by the transaction
        storeId: widget.storeId,
        customerId: customerId,
        customerName: widget.deliveryAddress.name,
        items: widget.items,
        totalAmount: widget.totalToPay,
        subTotal: widget.subtotal,
        deliveryFee: widget.deliveryFee,
        taxes: 0.0,
        platformFee: 0.0,
        paymentStatus: 'Pending',
        deliveryAddress: widget.deliveryAddress.formattedAddress,
        customerPhone: widget.deliveryAddress.phoneNumber,
        orderStatus: 'New',
        expiresAt: expiresAt,
        maxDispatchDate: maxDispatchDate,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      final generatedOrderId = await orderService.createOrder(order);

      // Clear the store's cart
      if (mounted) {
        Provider.of<CartProvider>(context, listen: false).clearStoreCart(widget.storeId);
        
        Navigator.pushAndRemoveUntil(
          context,
          MaterialPageRoute(builder: (_) => OrderSuccessScreen(
            orderId: generatedOrderId,
            amountPaid: widget.totalToPay,
            paymentMethod: _selectedMethod,
            date: DateTime.now(),
          )),
          (route) => route.isFirst, // Pop everything except Home
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text("Failed to place order: $e"), backgroundColor: Colors.red),
        );
      }
    } finally {
      if (mounted) setState(() => _isProcessing = false);
    }
  }

  Widget _buildPaymentOption({
    required String id,
    required String title,
    required String subtitle,
    required Widget icon,
    bool isRecommended = false,
    Widget? extraLogos,
  }) {
    final isSelected = _selectedMethod == id;
    
    return InkWell(
      onTap: () {
        if (id == 'COD') {
          setState(() => _selectedMethod = id);
        } else {
          _showComingSoon();
        }
      },
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: isSelected ? AppColors.primaryGreen.withOpacity(0.05) : Colors.white,
          border: Border.all(
            color: isSelected ? AppColors.primaryGreen : Colors.grey.shade200,
            width: isSelected ? 1.5 : 1.0,
          ),
          borderRadius: BorderRadius.circular(12),
        ),
        child: Column(
          children: [
            Row(
              children: [
                Container(
                  width: 40,
                  height: 40,
                  decoration: BoxDecoration(
                    color: Colors.grey.shade100,
                    borderRadius: BorderRadius.circular(8)
                  ),
                  child: Center(child: icon),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(title, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 15)),
                      const SizedBox(height: 4),
                      Text(subtitle, style: TextStyle(color: Colors.grey.shade600, fontSize: 12)),
                    ],
                  ),
                ),
                Container(
                  width: 20,
                  height: 20,
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    border: Border.all(
                      color: isSelected ? AppColors.primaryGreen : Colors.grey.shade400,
                      width: isSelected ? 6 : 1.5,
                    ),
                  ),
                )
              ],
            ),
            if (extraLogos != null) ...[
              const SizedBox(height: 12),
              extraLogos,
            ]
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFF9FAFB),
      appBar: AppBar(
        backgroundColor: const Color(0xFFF9FAFB),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: AppColors.textPrimary),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          "Select Payment Method",
          style: TextStyle(color: AppColors.textPrimary, fontSize: 18, fontWeight: FontWeight.bold),
        ),
      ),
      body: Column(
        children: [
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text("Recommended", style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),
                  const SizedBox(height: 12),
                  
                  _buildPaymentOption(
                    id: 'UPI',
                    title: 'UPI',
                    subtitle: 'Pay using any UPI app',
                    icon: const Icon(Icons.payment, color: AppColors.primaryGreen),
                    isRecommended: true,
                    extraLogos: Row(
                      children: [
                        const SizedBox(width: 56), // align with text
                        _buildMiniLogo('GPay', Colors.blue),
                        const SizedBox(width: 8),
                        _buildMiniLogo('PhonePe', Colors.deepPurple),
                        const SizedBox(width: 8),
                        _buildMiniLogo('Paytm', Colors.lightBlue),
                      ],
                    ),
                  ),
                  
                  const SizedBox(height: 24),
                  const Text("Other Methods", style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14)),
                  const SizedBox(height: 12),
                  
                  Container(
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(color: Colors.grey.shade200),
                    ),
                    child: Column(
                      children: [
                        _buildPaymentOption(
                          id: 'CARD',
                          title: 'Credit / Debit Card',
                          subtitle: 'Visa, Mastercard, RuPay',
                          icon: Icon(Icons.credit_card, color: Colors.blue.shade700),
                        ),
                        const Divider(height: 1),
                        _buildPaymentOption(
                          id: 'NETBANKING',
                          title: 'Net Banking',
                          subtitle: 'All major banks supported',
                          icon: Icon(Icons.account_balance, color: Colors.grey.shade700),
                        ),
                        const Divider(height: 1),
                        _buildPaymentOption(
                          id: 'WALLET',
                          title: 'Wallets',
                          subtitle: 'PhonePe, Paytm, Amazon Pay & more',
                          icon: const Icon(Icons.account_balance_wallet, color: Colors.orange),
                        ),
                        const Divider(height: 1),
                        _buildPaymentOption(
                          id: 'COD',
                          title: 'Cash on Delivery',
                          subtitle: 'Pay when your order is delivered',
                          icon: const Icon(Icons.money, color: AppColors.primaryGreen),
                        ),
                      ],
                    ),
                  ),
                  
                  const SizedBox(height: 24),
                  Container(
                    width: double.infinity,
                    padding: const EdgeInsets.all(16),
                    decoration: BoxDecoration(
                      color: Colors.green.shade50,
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(color: Colors.green.shade100),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text("Amount Payable", style: TextStyle(color: Colors.black54, fontSize: 13, fontWeight: FontWeight.w600)),
                        const SizedBox(height: 4),
                        Text("₹${widget.totalToPay.toInt()}", style: const TextStyle(fontWeight: FontWeight.w900, fontSize: 24)),
                      ],
                    ),
                  ),
                  
                  const SizedBox(height: 32),
                ],
              ),
            ),
          ),
          
          // Bottom Action Bar
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: Colors.white,
              boxShadow: [
                BoxShadow(color: Colors.black.withOpacity(0.05), blurRadius: 10, offset: const Offset(0, -5))
              ]
            ),
            child: SafeArea(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      const Icon(Icons.lock, size: 14, color: Colors.grey),
                      const SizedBox(width: 6),
                      Text("100% Secure Payments", style: TextStyle(color: Colors.grey.shade700, fontSize: 12, fontWeight: FontWeight.w500)),
                    ],
                  ),
                  const SizedBox(height: 12),
                  SizedBox(
                    width: double.infinity,
                    height: 54,
                    child: ElevatedButton(
                      onPressed: _isProcessing ? null : _placeOrder,
                      style: ElevatedButton.styleFrom(
                        backgroundColor: AppColors.primaryGreen,
                        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                        elevation: 0,
                      ),
                      child: _isProcessing 
                          ? const SizedBox(height: 20, width: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                          : Text("Place Order ₹${widget.totalToPay.toInt()}", style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 16)),
                    ),
                  ),
                ],
              ),
            ),
          )
        ],
      ),
    );
  }

  Widget _buildMiniLogo(String text, Color color) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
      decoration: BoxDecoration(
        color: color.withOpacity(0.1),
        borderRadius: BorderRadius.circular(4),
        border: Border.all(color: color.withOpacity(0.3)),
      ),
      child: Text(text, style: TextStyle(color: color, fontSize: 10, fontWeight: FontWeight.bold)),
    );
  }
}
